from fastapi import FastAPI, HTTPException
from supabase import create_client, Client
import serpapi
import os
from dotenv import load_dotenv
from typing import List, Optional

# Load environment variables
load_dotenv()

app = FastAPI()

# Configuration
SERP_API_KEY = os.getenv("SERP_API_KEY")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not all([SERP_API_KEY, SUPABASE_URL, SUPABASE_KEY]):
    raise ValueError("Missing environment variables. Please check .env file.")

# Initialize clients
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
# serpapi.Client does not exist in the official python library (google-search-results)
# We use GoogleSearch directly or a wrapper.
# However, to search using the client-like interface we need to use the class directly.
from serpapi import GoogleSearch


@app.get("/")
def read_root():
    return {"message": "Cafe Sync Service is running"}

@app.post("/sync")
def sync_cafes():
    try:
        print("Starting sync process...")
        
        # 1. Fetch data from SerpApi
        params = {
            "engine": "google",
            "type": "search",
            "q": "Coffeeshop in Yogyakarta",
            "ll": "@-7.7729949,110.3309142,13z",
            "start": "0",
            "num": "20" # Fetch up to 20 results
        }
        
        print(f"Searching for: {params['q']}")
        # Add api_key to params
        params["api_key"] = SERP_API_KEY
        search = GoogleSearch(params)
        results = search.get_dict()
        
        if "error" in results:
            raise HTTPException(status_code=500, detail=f"SerpApi error: {results['error']}")
            
        local_results = results.get("local_results", [])
        print(f"Found {len(local_results)} cafes from SerpApi")
        
        mapped_cafes = []
        
        # 2. Map and cleaning data
        for place in local_results:
            # Skip if no coordinates
            if "gps_coordinates" not in place:
                continue
                
            gps = place.get("gps_coordinates", {})
            
            # Extract main image if available
            # Note: SerpApi results might handle images differently, often in a separate 'thumbnail' field 
            # or 'images' list but the basic local result has 'thumbnail' often.
            
            cafe_data = {
                "name": place.get("title"),
                "address": place.get("address", "Unknown Address"),
                "phone": place.get("phone"),
                "latitude": gps.get("latitude"),
                "longitude": gps.get("longitude"),
                "rating": place.get("rating", 0),
                "review_count": place.get("reviews", 0),
                "is_active": True
                # Note: 'id' is generated by Supabase if we don't provide it, 
                # but to avoid duplicates we might want to check existence or use upsert with a unique constraint.
                # However, the 'cafes' table might not have a unique constraint on name/address.
                # For this simplest MVP, we will just insert. 
                # A better approach for sync is to check if it exists by name/lat/long.
            }
            
            # Simple deduplication check based on name (optional, but good practice)
            # data = supabase.from("cafes").select("id").eq("name", cafe_data["name"]).execute()
            # if data.data:
            #     print(f"Skipping {cafe_data['name']} (already exists)")
            #     continue
            
            mapped_cafes.append(cafe_data)

        if not mapped_cafes:
            return {"message": "No new cafes to sync", "count": 0}

        # 3. Insert into Supabase
        print(f"Upserting {len(mapped_cafes)} cafes to Supabase...")
        
        # Using upsert if possible, or insert. 
        # Since we don't have a clear unique key from SerpApi that matches our DB ID,
        # we will try to match by name to update, or insert if new.
        
        synced_count = 0
        for cafe in mapped_cafes:
            # Check if exists by name
            existing = supabase.table("cafes").select("id").eq("name", cafe["name"]).execute()
            
            if existing.data:
                # Update
                cafe_id = existing.data[0]['id']
                supabase.table("cafes").update(cafe).eq("id", cafe_id).execute()
                print(f"Updated: {cafe['name']}")
            else:
                # Insert
                supabase.table("cafes").insert(cafe).execute()
                print(f"Inserted: {cafe['name']}")
            
            synced_count += 1
            
        return {
            "message": "Sync completed successfully", 
            "synced_count": synced_count,
            "total_found": len(local_results)
        }

    except Exception as e:
        print(f"Error during sync: {e}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
